# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20170703_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 21, 46, 11, 668000, tzinfo=utc)),
        ),
    ]
